server:
  port: 8767

eureka:
  client:
    service-url:
      defaultZone: ${HS_FILES_EUREKA_URI:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#      hibernate: ERROR
