server:
  port: 8767

eureka:
  client:
    service-url:
      defaultZone: ${HS_FILES_EUREKA_URI:http://localhost:8761/eureka}

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui"

app:
  paintings:
    repository:
      fs:
        mount: ${HS_FILES_PAINTINGS_VOLUME:./pictures}
        locations:
          raw: "/raw"
          compressed: "/compressed"

spring:
  kafka:
    bootstrap-servers: ${HS_FILES_KAFKA_URI:http://localhost:9092}
    consumer:
      max-poll-records: 100
      auto-offset-reset: earliest

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#      hibernate: ERROR
